### ISSUE TITLE
Support WEBIRC

### ISSUE THREAD

**Issue by b3nw** [erming/shout#239]
Please support webirc to allow for proper handling of multiple clients by ircds:

Ref:
http://irc-wiki.org/WebIRC
http://wiki.mibbit.com/index.php/Enable_Mibbit_on_Your_IRC_Server
https://kiwiirc.com/docs/installing/webirc

**Comment by webvigo** [comment]
webirc it's necessary to run this webchat on the most important irc servers!

**Comment by spencerthayer** [comment]
@webvigo your opinion on what constitutes an important IRC server aside the fact that many servers require WEBIRC means that Shout isn't a fully functional client.

**Comment by webvigo** [comment]
@spencerthayer uhm? i said it would be a good feature to add in the future

**Comment by spencerthayer** [comment]
@webvigo SORRY! I miss read. : |

**Comment by webvigo** [comment]
@spencerthayer it doesn't matter :smile: with my poor english level confusions can happen :stuck_out_tongue:

**Comment by thedjpetersen** [comment]
Created a pull request for the client library https://github.com/slate/slate-irc/pull/26/files

**Comment by ronilaukkarinen** [comment]
@thedjpetersen Tried that, but doesn't work. Should it? or am being too impatient now...

**Comment by thedjpetersen** [comment]
@ronilaukkarinen I might have implemented it incorrectly

**Comment by spencerthayer** [comment]
This is a good sign! Can't wait to see how this works.

**Comment by spencerthayer** [comment]
Updates?

**Comment by ronilaukkarinen** [comment]
@thedjpetersen What do you mean? just tried the changes in your pull request, nothing more. I'm not expert on how this should work. Waiting here as well, eager to try new version. :+1:

**Comment by webvigo** [comment]
Before the client sends the PASS, USER or NICK commands it should send the WEBIRC command

**Comment by bopjesvla** [comment]
Here you go:

https://github.com/erming/shout/pull/343/files

It should probably be wrapped into `if (config.webirc == true) {...}`.

**Comment by spencerthayer** [comment]
FINALLY! I'll try this weekend.

**Comment by ronilaukkarinen** [comment]
Didn't get this to work. Just raw edited the files. Do I need to compile the bin/shout or something, seems like this edit didn't have any effect whatsoever. Node is not my main thing.

**Comment by bopjesvla** [comment]
I messed up the client's host name (fixed now!), but the IP should've been working.

Did you set webirc to true in default/config.js? Did you test it on a server that supports webirc?  Most big open servers seem to only allow their own webclients.

**Comment by spencerthayer** [comment]
@erming any chance of merging this to the master?

**Comment by ronilaukkarinen** [comment]
@bopjesvla I updated it and tested right now. I still get `Too many connections from your username - see https://www.quakenet.org/help/trusts/connection-limit for details.`

**Comment by bopjesvla** [comment]
Are you sure quakenet allows third parties to issue the WEBIRC command?

**Comment by b3nw** [comment]
You typically need to register with them for a trust. Once you've registered you can issue the webirc command with a password which will permit it via auth line. We do this on another large network as well.

**Comment by ronilaukkarinen** [comment]
@bopjesvla Yes, I think they do.
@b3nw I have trusts. How to issue the webirc command? this is new to me.

**Comment by iyx** [comment]
Please implement this, it's crucial feature.

**Comment by astorije** [comment]
@iyx, thanks for your interest. However, please note that Shout is the result of contributor working on it during their own free time, which makes it hard to respond to requests like this in a timely manner.
That being said, we welcome pull requests and, as a matter of fact, there is one ongoing (https://github.com/erming/shout/pull/379, which supersedes https://github.com/erming/shout/pull/343). I'll let you bring your comments there to make this shippable.

Also, as I do not know the first thing about WEBIRC, I'll let @JocelynDelalande (and potentially other core maintainers, @erming and/or @floogulinc) handle this project.

Finally, I think I'd like to see this becoming its own plugin (be it enabled by default or not does not impact its *pluginability*). @JocelynDelalande, would that make sense in the long run?
If so, I'd like to invite @iyx and other commenters on this thread to add their comments about a potential plugin system/WEBIRC plugin/else to the roadmap (https://github.com/erming/shout-roadmap). I know it's a long shot, but if someone wants to start and drive a plugin system project, its requirements and design reviews, that would be truly awesome...

Thanks all!

**Comment by vlanmx** [comment]
Guys, any update on this?

> @iyx, thanks for your interest. However, please note that Shout is the result of contributor working on it during their own free time, which makes it hard to respond to requests like this in a timely manner.

This is ridiculous, because the community gave you the code but you've closed the pull request.
Why don't you just pull https://github.com/erming/shout/pull/343/files or https://github.com/erming/shout/pull/343 and add extra configuration?
The @bopjesvla's and @AmShaegar13's code are enough base to implement it without any issue for you. Now, not having webirc support is a serious issue which makes this project very unuseful.

**Comment by vlanmx** [comment]
Guys, any update on this?

Lack of webirc support makes this project very unuseful.

**Comment by dgw** [comment]
Since @astorije's last comment on this thread, the community fork of Shout, The Lounge, has implemented WEBIRC (see thelounge/lounge#181).
